version: 2.1

jobs:
  build:
    docker:
      - image: ndavison/imagetest:latest
    steps:
      - checkout
      - run: sleep 30
    environment:
      FOO: bar'";\u0000
workflows:
  run-now:
    jobs:
      - build


